const products = [
  {
    id: "p-3001",
    name: "Adjustable Dumbbell Set 30kg",
    description: "Compact adjustable dumbbells for home workouts.",
    category: "fitness",
    price: 189,
    rating: 4.6,
    stock: 12,
    image: "https://picsum.photos/seed/dumbbell1/400/300",
  },
  {
    id: "p-3002",
    name: "Kettlebell 16kg Cast Iron",
    description: "Durable cast iron kettlebell for strength training.",
    category: "fitness",
    price: 59,
    rating: 4.5,
    stock: 20,
    image: "https://picsum.photos/seed/kettlebell1/400/300",
  },
  {
    id: "p-3003",
    name: "Yoga Mat Premium",
    description: "Non-slip yoga mat with extra cushioning.",
    category: "fitness",
    price: 35,
    rating: 4.2,
    stock: 45,
    image: "https://picsum.photos/seed/yogamat1/400/300",
  },
  {
    id: "p-3004",
    name: "Resistance Bands Set",
    description: "Set of 5 resistance bands for full-body training.",
    category: "fitness",
    price: 29,
    rating: 4.4,
    stock: 60,
    image: "https://picsum.photos/seed/bands/400/300",
  },
  {
    id: "p-3005",
    name: "Wireless Bluetooth Headphones",
    description: "Over-ear headphones with 25h battery life.",
    category: "electronics",
    price: 89,
    rating: 4.3,
    stock: 30,
    image: "https://picsum.photos/seed/headphones1/400/300",
  },
  {
    id: "p-3006",
    name: "Smartwatch Active",
    description: "Fitness smartwatch with heart rate and GPS tracking.",
    category: "electronics",
    price: 149,
    rating: 4.1,
    stock: 18,
    image: "https://picsum.photos/seed/smartwatch1/400/300",
  },
  {
    id: "p-3007",
    name: "USB-C Fast Charger 65W",
    description: "Compact GaN charger for laptops and smartphones.",
    category: "electronics",
    price: 39,
    rating: 4.7,
    stock: 40,
    image: "https://picsum.photos/seed/charger1/400/300",
  },
  {
    id: "p-3008",
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit keyboard with tactile switches.",
    category: "electronics",
    price: 99,
    rating: 4.5,
    stock: 22,
    image: "https://picsum.photos/seed/keyboard1/400/300",
  },
  {
    id: "p-3009",
    name: "Clean Code",
    description: "A Handbook of Agile Software Craftsmanship.",
    category: "books",
    price: 28,
    rating: 4.8,
    stock: 9,
    image: "https://picsum.photos/seed/bookclean/400/300",
  },
  {
    id: "p-3010",
    name: "JavaScript: The Good Parts",
    description: "Essential guide to mastering JavaScript.",
    category: "books",
    price: 24,
    rating: 4.4,
    stock: 14,
    image: "https://picsum.photos/seed/bookjs/400/300",
  },
  {
    id: "p-3011",
    name: "Practical TypeScript",
    description: "Modern TypeScript patterns and real-world examples.",
    category: "books",
    price: 32,
    rating: 4.6,
    stock: 11,
    image: "https://picsum.photos/seed/bookts/400/300",
  },
  {
    id: "p-3012",
    name: "Deep Work",
    description: "Rules for focused success in a distracted world.",
    category: "books",
    price: 22,
    rating: 4.7,
    stock: 17,
    image: "https://picsum.photos/seed/bookdeep/400/300",
  },
];

module.exports = { products };
