const products = [
  {
    id: "p-4001",
    name: "Wireless Headphones",
    description:
      "Comfortable over-ear headphones with deep bass and clear sound.",
    category: "electronics",
    price: 89,
    rating: 4.4,
    stock: 28,
    imageUrl: "/images/headphones.jpg",
    specs: { battery: "30h", connectivity: "BT 5.2" },
  },
  {
    id: "p-4002",
    name: "Bluetooth Speaker Mini",
    description: "Portable speaker with punchy sound and 10h battery.",
    category: "electronics",
    price: 39,
    rating: 4.3,
    stock: 50,
    imageUrl: "/images/BluetoothSpeaker.webp",
    specs: { battery: "10h", power: "8W" },
  },
  {
    id: "p-4003",
    name: "Smartwatch Sport",
    description: "Track steps, workouts, sleep, and notifications.",
    category: "electronics",
    price: 129,
    rating: 4.1,
    stock: 17,
    imageUrl: "/images/sportsmartwatch.webp",
    specs: { waterResistance: "5ATM", sensors: "HR, SpO2" },
  },
  {
    id: "p-4004",
    name: "USB-C Fast Charger 65W",
    description: "Fast charging for phones and laptops with compact design.",
    category: "electronics",
    price: 35,
    rating: 4.7,
    stock: 40,
    imageUrl: "/images/usbcwallcharger.webp",
    specs: { power: "65W", ports: "USB-C" },
  },
  {
    id: "p-4005",
    name: "Adjustable Dumbbells 20kg",
    description: "Two adjustable dumbbells for strength workouts at home.",
    category: "fitness",
    price: 169,
    rating: 4.6,
    stock: 12,
    imageUrl: "/images/dumbbell.jpg",
    specs: { maxWeight: "20kg each", material: "steel" },
  },
  {
    id: "p-4006",
    name: "Kettlebell 16kg",
    description: "Cast iron kettlebell for strength and conditioning training.",
    category: "fitness",
    price: 59,
    rating: 4.5,
    stock: 18,
    imageUrl: "/images/blackkettlebell.webp",
    specs: { weight: "16kg", material: "cast iron" },
  },
  {
    id: "p-4007",
    name: "Yoga Mat Pro",
    description: "Non-slip yoga mat with extra grip and comfort (6mm).",
    category: "fitness",
    price: 29,
    rating: 4.2,
    stock: 55,
    imageUrl: "/images/rolledyogamat.jpg",
    specs: { thickness: "6mm", surface: "non-slip" },
  },
  {
    id: "p-4008",
    name: "Resistance Bands Set",
    description: "Set of 5 bands for full-body training and stretching.",
    category: "fitness",
    price: 19,
    rating: 4.4,
    stock: 80,
    imageUrl: "/images/resistancebandsset.webp",
    specs: { count: "5", levels: "light–heavy" },
  },
  {
    id: "p-4009",
    name: "Air Fryer 5L",
    description: "Crispy food with little oil using simple digital controls.",
    category: "home",
    price: 119,
    rating: 4.6,
    stock: 14,
    imageUrl: "/images/airfryer.webp",
    specs: { capacity: "5L", control: "digital" },
  },
  {
    id: "p-4010",
    name: "Electric Kettle 1.7L",
    description: "Fast boiling kettle with auto shut-off and easy pour.",
    category: "home",
    price: 34,
    rating: 4.5,
    stock: 33,
    imageUrl: "/images/electrickettle.webp",
    specs: { capacity: "1.7L", feature: "auto shut-off" },
  },
  {
    id: "p-4011",
    name: "Bedside Lamp",
    description: "Warm light lamp with touch control and 3 brightness levels.",
    category: "home",
    price: 27,
    rating: 4.3,
    stock: 60,
    imageUrl: "/images/bedsidelamp.webp",
    specs: { control: "touch", levels: "3" },
  },
  {
    id: "p-4012",
    name: "Vacuum Cleaner Compact",
    description: "Lightweight vacuum for quick cleaning in small spaces.",
    category: "home",
    price: 149,
    rating: 4.1,
    stock: 9,
    imageUrl: "/images/vacuumcleaner.webp",
    specs: { weight: "light", type: "compact" },
  },
];

const users = [
  { id: "u-1", email: "customer@test.com", name: "Customer", role: "customer" },
  { id: "u-2", email: "admin@test.com", name: "Dima Admin", role: "admin" },
];

const orders = [];

module.exports = { products, users, orders };
